services:
  db:
    image: informaticsmatters/rdkit-cartridge-debian:latest
    environment:
      POSTGRES_DB: hab_db
      POSTGRES_USER: chem
      POSTGRES_PASSWORD: chem
    ports: ["5432:5432"]
