"""Added E0

Revision ID: 06b6289c4edb
Revises: 68e38247aaf8
Create Date: 2025-09-01 22:43:40.034300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06b6289c4edb"
down_revision: Union[str, Sequence[str], None] = "68e38247aaf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("well_features", sa.Column("E0", sa.Float(), nullable=True))
    op.add_column("well_features", sa.Column("E0_units", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("well_features", "E0_units")
    op.drop_column("well_features", "E0")
    # ### end Alembic commands ###
