"""Adding in is_ts to species table

Revision ID: 227088b31fcc
Revises: 3d978523d565
Create Date: 2025-08-26 09:54:36.928568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "227088b31fcc"
down_revision: Union[str, Sequence[str], None] = "3d978523d565"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("species", sa.Column("is_ts", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("species", "is_ts")
    # ### end Alembic commands ###
