"""Added element count to Species

Revision ID: 68e38247aaf8
Revises: 6f6c3e340c7f
Create Date: 2025-08-31 15:05:34.609150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68e38247aaf8"
down_revision: Union[str, Sequence[str], None] = "6f6c3e340c7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "species",
        sa.Column(
            "elements_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("species", sa.Column("heavy_atoms", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("species", "heavy_atoms")
    op.drop_column("species", "elements_json")
    # ### end Alembic commands ###
