"""Removed columns from TSFeatures

Revision ID: 69e0f4d37d22
Revises: 9132b91c1138
Create Date: 2025-08-26 23:51:48.986292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69e0f4d37d22"
down_revision: Union[str, Sequence[str], None] = "9132b91c1138"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ts_features", "E_R1H")
    op.drop_column("ts_features", "E_R2H")
    op.drop_column("ts_features", "delta_E_dagger")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ts_features",
        sa.Column(
            "delta_E_dagger",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ts_features",
        sa.Column(
            "E_R2H",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ts_features",
        sa.Column(
            "E_R1H",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
