"""Added Names for Species

Revision ID: 6f6c3e340c7f
Revises: c61fadbe56d5
Create Date: 2025-08-30 19:47:42.498838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f6c3e340c7f"
down_revision: Union[str, Sequence[str], None] = "c61fadbe56d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_identifier",
        sa.Column("ext_id", sa.BigInteger(), nullable=False),
        sa.Column("species_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "db",
            sa.Enum("pubchem", "chemspider", "cas", "other", name="externaldb"),
            nullable=False,
        ),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["species_id"], ["species.species_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ext_id"),
        sa.UniqueConstraint("species_id", "db", name="uq_species_db_once"),
    )
    op.create_index(
        op.f("ix_external_identifier_species_id"),
        "external_identifier",
        ["species_id"],
        unique=False,
    )
    op.create_index(
        "ix_extid_db_identifier",
        "external_identifier",
        ["db", "identifier"],
        unique=False,
    )
    op.create_table(
        "species_name",
        sa.Column("name_id", sa.BigInteger(), nullable=False),
        sa.Column("species_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("lang", sa.String(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "pubchem", "rmg", "opsin", "user", "cactus", "other", name="namesource"
            ),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("curated", sa.Boolean(), nullable=False),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["species_id"], ["species.species_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("name_id"),
        sa.UniqueConstraint("species_id", "name", name="uq_species_name"),
    )
    op.create_index(
        op.f("ix_species_name_species_id"), "species_name", ["species_id"], unique=False
    )
    op.create_index("ix_species_name_trgm", "species_name", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_species_name_trgm", table_name="species_name")
    op.drop_index(op.f("ix_species_name_species_id"), table_name="species_name")
    op.drop_table("species_name")
    op.drop_index("ix_extid_db_identifier", table_name="external_identifier")
    op.drop_index(
        op.f("ix_external_identifier_species_id"), table_name="external_identifier"
    )
    op.drop_table("external_identifier")
    # ### end Alembic commands ###
