"""Added indexes to Species

Revision ID: 71adc75ecb79
Revises: 06b6289c4edb
Create Date: 2025-09-02 13:28:01.003223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71adc75ecb79"
down_revision: Union[str, Sequence[str], None] = "06b6289c4edb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_species_elements",
        "species",
        ["elements_json"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_species_heavy_atoms", "species", ["heavy_atoms"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_species_heavy_atoms", table_name="species")
    op.drop_index("ix_species_elements", table_name="species", postgresql_using="gin")
    # ### end Alembic commands ###
