"""Adding units to geom_*

Revision ID: 764f58da2876
Revises: a1cc08abc5bb
Create Date: 2025-08-25 23:29:22.944792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764f58da2876'
down_revision: Union[str, Sequence[str], None] = 'a1cc08abc5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geom_angle', sa.Column('units', sa.String(), nullable=False))
    op.add_column('geom_dihedral', sa.Column('units', sa.String(), nullable=False))
    op.add_column('geom_distance', sa.Column('units', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geom_distance', 'units')
    op.drop_column('geom_dihedral', 'units')
    op.drop_column('geom_angle', 'units')
    # ### end Alembic commands ###
