"""Removed is_ts from Species and added well_rank to conformer

Revision ID: ba1e888f2fbc
Revises: 227088b31fcc
Create Date: 2025-08-26 10:01:32.036074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba1e888f2fbc"
down_revision: Union[str, Sequence[str], None] = "227088b31fcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conformer", sa.Column("well_rank", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_conformer_well"), table_name="conformer")
    op.create_index(
        "ix_conformer_species_lot_rank",
        "conformer",
        ["species_id", "lot_id", "well_rank"],
        unique=False,
    )
    op.drop_column("species", "is_ts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "species", sa.Column("is_ts", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_index("ix_conformer_species_lot_rank", table_name="conformer")
    op.create_index(
        op.f("ix_conformer_well"), "conformer", ["well_label"], unique=False
    )
    op.drop_column("conformer", "well_rank")
    # ### end Alembic commands ###
