"""Added G298 Calc

Revision ID: c61fadbe56d5
Revises: f5dee4c637d4
Create Date: 2025-08-28 19:46:31.627793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c61fadbe56d5"
down_revision: Union[str, Sequence[str], None] = "f5dee4c637d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("reactions_reaction_name_key"), "reactions", type_="unique")
    op.add_column("well_features", sa.Column("G298_source", sa.String(), nullable=True))
    op.add_column("well_features", sa.Column("G_calc_T_K", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("well_features", "G_calc_T_K")
    op.drop_column("well_features", "G298_source")
    op.create_unique_constraint(
        op.f("reactions_reaction_name_key"),
        "reactions",
        ["reaction_name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
