"""Added is_well__representative to Conformer in regards to Well Energy ranking

Revision ID: f5dee4c637d4
Revises: 69e0f4d37d22
Create Date: 2025-08-27 17:52:08.633025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5dee4c637d4"
down_revision: Union[str, Sequence[str], None] = "69e0f4d37d22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conformer", sa.Column("is_well_representative", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conformer", "is_well_representative")
    # ### end Alembic commands ###
